version: "2.4"
networks:
    VLAN_heimdall:
        external: true
        name: VLAN_heimdall
    VLAN_pi-hole:
        external: true
        name: VLAN_pi-hole
services:
    heimdall:
        container_name: heimdall
        image: ghcr.io/linuxserver/heimdall
        volumes: /home/docker/heimdall/config:/config
        restart: always
        environment:
            PGID: ${PGID}
            PUID: ${PUID}
            TZ: US/Eastern
        networks:
            VLAN_pi-hole:
                ipv4_address: ${HEIMDALL_STATIC_IP}
        mac_address: ${HEIMDALL_MAC_ADDRESS}
    pi-hole:
        container_name: pihole
        image: pihole/pihole:latest
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /home/docker/pi-hole/config:/etc/pihole
            - /home/docker/pi-hole/dnsmasq:/etc/dnsmasq.d
        cap_add:
            - NET_ADMIN
        environment:
            PIHOLE_DNS_: 1.1.1.1;1.0.0.1
            ServerIP: ${PIHOLE_STATIC_IP}
            DNSMASQ_LISTENING: local
            WEBPASSWORD: ${PIHOLE_WEBPASSWORD}
            TZ: US/Eastern
        networks:
            VLAN_pi-hole:
                ipv4_address: ${PIHOLE_STATIC_IP}
        mac_address: ${PIHOLE_MAC_ADDRESS}
        restart: always
    rpi-monitor:
        container_name: rpi-monitor
        image: michaelmiklis/rpi-monitor:latest
        devices:
            - /dev/vchiq
            - /dev/vcsm-cma
        volumes:
            - /opt/vc:/opt/vc
            - /boot:/boot
            - /sys:/dockerhost/sys:ro
            - /etc:/dockerhost/etc:ro
            - /proc:/dockerhost/proc:ro
            - /usr/lib:/dockerhost/usr/lib:ro
        ports:
            - 8888:8888
        restart: always
