version: "2.4"
services:
    pi-hole:
        container_name: pihole
        image: pihole/pihole:latest
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /home/docker/pi-hole/config:/etc/pihole
            - /home/docker/pi-hole/dnsmasq:/etc/dnsmasq.d
        cap_add:
            - NET_ADMIN
        environment:
            PIHOLE_DNS_: 1.1.1.1;1.0.0.1
            ServerIP: 192.168.1.5
            DNSMASQ_LISTENING: local
            WEBPASSWORD: "PkB9VR@Hoxb-vb"
            TZ: "US/Eastern"
        networks:
            VLAN_pi-hole:
                ipv4_address: 192.168.1.5
        mac_address: 02:42:c0:a8:01:d8
        restart: always
    rpi-monitor:
        container_name: rpi-monitor
        image: michaelmiklis/rpi-monitor:latest
        devices:
            - "/dev/vchiq"
            - "/dev/vcsm-cma"
        volumes:
            - /opt/vc:/opt/vc
            - /boot:/boot
            - /sys:/dockerhost/sys:ro
            - /etc:/dockerhost/etc:ro
            - /proc:/dockerhost/proc:ro
            - /usr/lib:/dockerhost/usr/lib:ro
        ports:
            - "8888:8888"
        restart: always
