version: "2.4"
networks:
    VLAN_pi-hole:
        external: true
        name: VLAN_pi-hole
services:
    pi-hole:
        container_name: pihole
        image: pihole/pihole:latest
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /opt/pi-hole/config:/etc/pihole
            - /opt/pi-hole/dnsmasq:/etc/dnsmasq.d
        cap_add:
            - NET_ADMIN
        environment:
            PIHOLE_DNS_: 1.1.1.1;1.0.0.1
            ServerIP: ${PIHOLE_STATIC_IP}
            DNSMASQ_LISTENING: local
            WEBPASSWORD: ${PIHOLE_WEBPASSWORD}
            TZ: US/Eastern
        ports:
            - "53:53/tcp"
            - "53:53/udp"
            - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
            - "80:80/tcp"
        networks:
            VLAN_pi-hole:
                ipv4_address: ${PIHOLE_STATIC_IP}
        mac_address: ${PIHOLE_MAC_ADDRESS}
        restart: always
    rpi-monitor:
        container_name: rpi-monitor
        image: michaelmiklis/rpi-monitor:latest
        devices:
            - /dev/vchiq
            - /dev/vcsm-cma
        volumes:
            - /opt/vc:/opt/vc
            - /boot:/boot
            - /sys:/dockerhost/sys:ro
            - /etc:/dockerhost/etc:ro
            - /proc:/dockerhost/proc:ro
            - /usr/lib:/dockerhost/usr/lib:ro
        ports:
            - 8888:8888
        restart: always
